import type { CssException } from './cssGuard';

/**
 * gallery.css is layout only, apart from these. Group B: token specimens that must paint to show a
 * token. Group C: the gallery frame and accessibility. One entry per selector and property; the test
 * fails on anything new that is not listed here, and on entries that no longer match.
 */
export const GALLERY_CSS_EXCEPTIONS: readonly CssException[] = [
  // ---------------------------------------------------------------- B: token specimens
  { selector: '.gallery-face[data-face="display"]', property: 'font-family', reason: 'specimen: shows the display type face' },
  { selector: '.gallery-face[data-face="display"]', property: 'font-weight', reason: 'specimen: shows the display type face' },
  { selector: '.gallery-face[data-face="body"]', property: 'font-family', reason: 'specimen: shows the body type face' },
  { selector: '.gallery-face[data-face="body"]', property: 'font-weight', reason: 'specimen: shows the body type face' },
  { selector: '.gallery-face[data-face="pixel"]', property: 'font-family', reason: 'specimen: shows the pixel type face' },
  { selector: '.gallery-face[data-face="pixel"]', property: 'font-weight', reason: 'specimen: shows the pixel type face' },
  { selector: '.gallery-face[data-face="pixel"]', property: 'font-size', reason: 'specimen: shows the pixel type face' },
  { selector: '.gallery-face[data-face="pixel"]', property: 'text-transform', reason: 'specimen: shows the pixel type face' },
  { selector: '.gallery-face[data-face="mono"]', property: 'font-family', reason: 'specimen: shows the mono type face' },
  { selector: '.gallery-face[data-face="mono"]', property: 'font-weight', reason: 'specimen: shows the mono type face' },
  { selector: '.gallery-face[data-face="mono"]', property: 'font-size', reason: 'specimen: shows the mono type face' },
  { selector: '.gallery-ruler__bar', property: 'background', reason: 'specimen: shows a spacing token as a bar' },
  { selector: '@media (forced-colors: active) .gallery-ruler__bar', property: 'forced-color-adjust', reason: 'forced colours: keeps the spacing bar visible' },
  { selector: '@media (forced-colors: active) .gallery-ruler__bar', property: 'background', reason: 'forced colours: keeps the spacing bar visible' },
  { selector: '.bit-box.gallery-outline', property: 'outline', reason: 'specimen: shows the extent of a Box' },
  { selector: '.gallery-preview__stage > .bit-box', property: 'outline', reason: 'specimen: shows the extent of a Box' },
  { selector: '.gallery-preview[data-checkerboard] .gallery-preview__stage', property: 'background-image', reason: 'specimen: checkerboard shows transparency' },
  { selector: '.gallery-preview[data-checkerboard] .gallery-preview__stage', property: 'background-size', reason: 'specimen: checkerboard shows transparency' },
  { selector: '.gallery-preview[data-checkerboard] .gallery-preview__stage', property: 'background-position', reason: 'specimen: checkerboard shows transparency' },
  { selector: '.gallery-swatch', property: 'border', reason: 'specimen: outlines a colour swatch' },
  { selector: '.gallery-swatch', property: 'border-radius', reason: 'specimen: rounds a colour swatch' },
  { selector: '.gallery-shape', property: 'background', reason: 'specimen: shows a radius or shadow token' },
  { selector: '.gallery-shape', property: 'border', reason: 'specimen: shows a radius or shadow token' },
  // ---------------------------------------------------------------- C: frame and accessibility
  { selector: 'html', property: 'scroll-behavior', reason: 'frame: smooth anchor scrolling' },
  { selector: '.gallery-skip', property: 'background', reason: 'a11y: the skip link shows as a chip when it has focus' },
  { selector: '.gallery-skip', property: 'color', reason: 'a11y: the skip link shows as a chip when it has focus' },
  { selector: '.gallery-skip', property: 'border', reason: 'a11y: the skip link shows as a chip when it has focus' },
  { selector: '.gallery-skip', property: 'border-radius', reason: 'a11y: the skip link shows as a chip when it has focus' },
  { selector: '.gallery-skip', property: 'transform', reason: 'a11y: keeps the skip link off-screen until it has focus' },
  { selector: '.gallery-skip:focus', property: 'transform', reason: 'a11y: slides the skip link into view on focus' },
  { selector: '.gallery-header', property: 'background', reason: 'frame: header surface and divider' },
  { selector: '.gallery-header', property: 'border-bottom', reason: 'frame: header surface and divider' },
  { selector: '.gallery-header__brand', property: 'text-decoration', reason: 'frame: the brand link is not underlined' },
  { selector: '.gallery-sidebar', property: 'border-right', reason: 'frame: sidebar surface and divider' },
  { selector: '.gallery-sidebar', property: 'background', reason: 'frame: sidebar surface and divider' },
  { selector: '.gallery-sidebar__title', property: 'font-family', reason: 'label face: Text has no face prop (spec amendment 2)' },
  { selector: '.gallery-sidebar__title', property: 'text-transform', reason: 'label face: Text has no face prop (spec amendment 2)' },
  { selector: '.gallery-sidebar__title', property: 'letter-spacing', reason: 'label face: Text has no face prop (spec amendment 2)' },
  { selector: '.gallery-sidebar__list', property: 'list-style', reason: 'frame: no bullets on the nav list' },
  { selector: '.gallery-sidebar__link.bit-link.bit-neutral', property: 'border-radius', reason: 'frame: sidebar link look, set above bit Link' },
  { selector: '.gallery-sidebar__link.bit-link.bit-neutral', property: 'color', reason: 'frame: sidebar link look, set above bit Link' },
  { selector: '.gallery-sidebar__link.bit-link.bit-neutral', property: 'text-decoration', reason: 'frame: sidebar link look, set above bit Link' },
  { selector: '.gallery-sidebar__link.bit-link.bit-neutral', property: 'font-weight', reason: 'frame: sidebar link look, set above bit Link' },
  { selector: '.gallery-sidebar__link.bit-link.bit-neutral:hover', property: 'background', reason: 'frame: sidebar link hover' },
  { selector: '.gallery-sidebar__link.bit-link.bit-neutral.active, .gallery-sidebar__link.bit-link.bit-neutral.active:hover, .gallery-sidebar__link.bit-link.bit-neutral.active:visited', property: 'background', reason: 'frame: sidebar active page' },
  { selector: '.gallery-sidebar__link.bit-link.bit-neutral.active, .gallery-sidebar__link.bit-link.bit-neutral.active:hover, .gallery-sidebar__link.bit-link.bit-neutral.active:visited', property: 'color', reason: 'frame: sidebar active page' },
  { selector: '.gallery-main:focus, .gallery-main [tabindex="-1"]:focus', property: 'outline', reason: 'focus: no ring on the main area, which only takes focus from the skip link and route changes' },
  { selector: '.gallery-link-list', property: 'list-style', reason: 'frame: no bullets on the link list' },
  { selector: '.gallery-eyebrow', property: 'font-family', reason: 'label face: Text has no face prop (spec amendment 2)' },
  { selector: '.gallery-eyebrow', property: 'text-transform', reason: 'label face: Text has no face prop (spec amendment 2)' },
  { selector: '.gallery-eyebrow', property: 'letter-spacing', reason: 'label face: Text has no face prop (spec amendment 2)' },
  { selector: '.gallery-section-bar', property: 'border-block', reason: 'frame: divider lines around a section heading' },
  { selector: '.gallery-preview__bar', property: 'border-bottom', reason: 'frame: preview toolbar surface and divider' },
  { selector: '.gallery-preview__bar', property: 'background', reason: 'frame: preview toolbar surface and divider' },
  { selector: '.gallery-preview__title', property: 'font-family', reason: 'label face: Text has no face prop (spec amendment 2)' },
  { selector: '.gallery-preview__title', property: 'font-size', reason: 'label face: Text has no face prop (spec amendment 2)' },
  { selector: '.gallery-preview__title', property: 'text-transform', reason: 'label face: Text has no face prop (spec amendment 2)' },
  { selector: '.gallery-preview__title', property: 'letter-spacing', reason: 'label face: Text has no face prop (spec amendment 2)' },
  { selector: '.gallery-tile__preview', property: 'border-bottom', reason: 'frame: divider between a tile preview and its caption' },
  { selector: '.gallery-tile__link::after', property: 'content', reason: 'frame: stretched link makes the whole tile clickable' },
  { selector: '.gallery-tile:has(.gallery-tile__link:focus-visible)', property: 'outline', reason: 'focus: visible ring for the whole tile' },
  { selector: '.gallery-tile:has(.gallery-tile__link:focus-visible)', property: 'outline-offset', reason: 'focus: visible ring for the whole tile' },
  { selector: '.gallery-tile__link:focus-visible', property: 'outline', reason: 'focus: removes the own ring of the link because the whole tile draws it' },
];
