// Builds bit's icons from packages/core/src/icons/icons.json and the pinned @material-symbols/svg-700
// (a devDependency of @bit-ds/react). Writes two committed files:
//   packages/react/src/icons/icons.generated.ts   one IconData const per icon, plus ICON_GROUPS
//   packages/core/src/icons/icons.generated.css   one --_bit-icon mask rule per icon (shipped as icons.css)
// Run `npm run icons` after editing icons.json. scripts/build-icons.test.mjs fails when they drift.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { iconClassName, iconExportName, iconName } from './icon-names.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const requireFromReact = createRequire(resolve(root, 'packages/react/package.json'));
const PACKAGE = '@material-symbols/svg-700';

export const OUTPUTS = {
  list: resolve(root, 'packages/core/src/icons/icons.json'),
  ts: resolve(root, 'packages/react/src/icons/icons.generated.ts'),
  css: resolve(root, 'packages/core/src/icons/icons.generated.css'),
};

const SOURCE = /^<svg xmlns="http:\/\/www\.w3\.org\/2000\/svg" width="48" height="48" viewBox="0 -960 960 960"><path d="([^"]+)"\/><\/svg>\n?$/;
const EXPORT = /^icon[A-Z][A-Za-z0-9]*$/;

/** The one path in a Material file; throws when the file is anything else. */
function pathOf(file, svg) {
  const match = SOURCE.exec(svg);
  if (!match) throw new Error(`build-icons: ${file} is not a single 960-grid path`);
  return match[1];
}

/** The SVG as a CSS url(): only the characters a data URI needs are escaped, so the file stays small. */
function dataUri(path) {
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 -960 960 960'><path d='${path}'/></svg>`;
  return `url("data:image/svg+xml,${svg.replace(/%/g, '%25').replace(/#/g, '%23').replace(/</g, '%3C').replace(/>/g, '%3E')}")`;
}

/**
 * The two files' text. `groups` is icons.json; `readSvg(file)` returns a file from the package's sharp/ folder.
 * Pure: the same input always gives the same output.
 */
export function buildIcons({ groups, readSvg, version }) {
  const seen = new Set();
  const icons = []; // { material, exportName, name, path }, regular then fill, in list order
  const groupLines = [];
  for (const [label, names] of Object.entries(groups)) {
    const pairs = [];
    for (const regular of names) {
      if (seen.has(regular)) throw new Error(`build-icons: listed twice: ${regular}`);
      seen.add(regular);
      const pair = [regular, `${regular}-fill`].map((material) => {
        const exportName = iconExportName(material);
        if (!EXPORT.test(exportName)) throw new Error(`build-icons: ${material} does not make a valid export name`);
        const icon = { material, exportName, name: iconName(material), path: pathOf(`${material}.svg`, readSvg(`${material}.svg`)) };
        icons.push(icon);
        return icon;
      });
      pairs.push(`{ regular: ${pair[0].exportName}, fill: ${pair[1].exportName} }`);
    }
    groupLines.push(`  { label: '${label.replace(/'/g, "\\'")}', icons: [${pairs.join(', ')}] },`);
  }
  const ts = [
    `// Generated by scripts/build-icons.mjs from packages/core/src/icons/icons.json and ${PACKAGE} ${version}. Do not edit.`,
    '// Artwork: Material Symbols Sharp 700, Copyright Google LLC, Apache License 2.0.',
    "import type { IconData, IconGroup } from './types';",
    '',
    ...icons.map((i) => `export const ${i.exportName}: IconData = { name: '${i.name}', path: '${i.path}' };`),
    '',
    "/** The curated set in the gallery's order: each group's icons with their fill versions. */",
    'export const ICON_GROUPS: readonly IconGroup[] = [',
    ...groupLines,
    '];',
    '',
  ].join('\n');
  const css = [
    '/* Generated by scripts/build-icons.mjs. Do not edit. Shipped as @bit-ds/react/icons.css, never inside styles.css. */',
    `/* Artwork: Material Symbols Sharp 700 (${PACKAGE} ${version}), Apache License 2.0, Copyright Google LLC. */`,
    ...icons.map((i) => `.${iconClassName(i.material)}{--_bit-icon:${dataUri(i.path)}}`),
    '',
  ].join('\n');
  return { ts, css };
}

/** icons.json, a reader over the pinned package's sharp/ folder, and that package's version. */
export function loadInputs() {
  const groups = JSON.parse(readFileSync(OUTPUTS.list, 'utf8'));
  const pkgJson = requireFromReact.resolve(`${PACKAGE}/package.json`);
  const sharp = resolve(dirname(pkgJson), 'sharp');
  const { version } = JSON.parse(readFileSync(pkgJson, 'utf8'));
  return { groups, readSvg: (file) => readFileSync(resolve(sharp, file), 'utf8'), version };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { ts, css } = buildIcons(loadInputs());
  writeFileSync(OUTPUTS.ts, ts);
  writeFileSync(OUTPUTS.css, css);
  console.log(`build-icons: wrote ${(ts.match(/^export const icon/gm) ?? []).length} icons`);
}
