// The icon generator: naming, the generated files' shape, and drift between icons.json, the pinned artwork
// and the committed output.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { iconName, iconExportName, iconClassName } from './icon-names.mjs';
import { buildIcons, loadInputs, OUTPUTS } from './build-icons.mjs';

const SVG = (d) => `<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 -960 960 960"><path d="${d}"/></svg>`;
const fakeRead = (file) => SVG(`M0 0h${file.length}`);

test('names: underscores become hyphens; exports are icon + PascalCase; classes are bit-icon-{name}', () => {
  assert.equal(iconName('keyboard_arrow_down'), 'keyboard-arrow-down');
  assert.equal(iconName('favorite-fill'), 'favorite-fill');
  assert.equal(iconExportName('keyboard_arrow_down'), 'iconKeyboardArrowDown');
  assert.equal(iconExportName('check_circle-fill'), 'iconCheckCircleFill');
  assert.equal(iconExportName('strikethrough_s'), 'iconStrikethroughS');
  assert.equal(iconClassName('arrow_back-fill'), 'bit-icon-arrow-back-fill');
});

test('buildIcons writes one const and one CSS rule per icon, and groups in list order', () => {
  const { ts, css } = buildIcons({ groups: { Actions: ['add', 'arrow_back'] }, readSvg: fakeRead, version: '0.47.6' });
  assert.match(ts, /^\/\/ Generated by scripts\/build-icons\.mjs/);
  assert.equal((ts.match(/^export const icon/gm) ?? []).length, 2);
  assert.match(ts, /export const iconAdd: IconData = \{ name: 'add', path: 'M0 0h\d+', fillPath: 'M0 0h\d+' \};/);
  assert.match(ts, /export const ICON_GROUPS: readonly IconGroup\[\] = \[\n {2}\{ label: 'Actions', icons: \[iconAdd, iconArrowBack\] \},\n\];/);
  assert.match(css, /Material Symbols Sharp 700 \(@material-symbols\/svg-700 0\.47\.6\), Apache License 2\.0/);
  const rule = /^\.bit-icon-[a-z0-9-]+\{--_bit-icon:url\("data:image\/svg\+xml,[^"]+"\);--_bit-icon-fill:url\("data:image\/svg\+xml,[^"]+"\)\}$/gm;
  assert.equal((css.match(rule) ?? []).length, 2);
  // Layered like styles.css, with the same order statement first, so it holds whichever file loads first.
  assert.match(css, /\n@layer bit\.reset, bit\.tokens, bit\.components;\n@layer bit\.components \{\n\.bit-icon-add\{/);
  assert.match(css, /\}\n\}\n$/);
  assert.doesNotMatch(ts, /Fill\b|-fill'/);
  assert.doesNotMatch(css, /\.bit-icon-[a-z0-9-]*-fill\{/);
});

test('buildIcons rejects two names that map to one export', () => {
  assert.throws(
    () => buildIcons({ groups: { A: ['arrow_back', 'arrow-back'] }, readSvg: fakeRead, version: '1' }),
    /arrow-back maps to the same export as arrow_back/,
  );
});

test('buildIcons is deterministic', () => {
  const input = { groups: { A: ['add'], B: ['close'] }, readSvg: fakeRead, version: '1' };
  assert.deepEqual(buildIcons(input), buildIcons(input));
});

test('buildIcons rejects artwork that is not exactly one path on the 960 grid', () => {
  const bad = () => '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g><path d="M0 0"/></g></svg>';
  assert.throws(() => buildIcons({ groups: { A: ['add'] }, readSvg: bad, version: '1' }), /add\.svg is not a single 960-grid path/);
});

test('buildIcons rejects duplicates and names that make a bad identifier', () => {
  assert.throws(() => buildIcons({ groups: { A: ['add'], B: ['add'] }, readSvg: fakeRead, version: '1' }), /listed twice: add/);
  assert.throws(() => buildIcons({ groups: { A: ['10k'] }, readSvg: fakeRead, version: '1' }), /10k does not make a valid export name/);
});

test('the real list: 8 groups, 300 names, 300 icons', () => {
  const { groups } = loadInputs();
  assert.equal(Object.keys(groups).length, 8);
  assert.equal(Object.values(groups).flat().length, 300);
  const { ts, css } = buildIcons(loadInputs());
  assert.equal((ts.match(/^export const icon/gm) ?? []).length, 300);
  assert.equal((css.match(/^\.bit-icon-/gm) ?? []).length, 300);
});

test('the committed generated files match a fresh run (run `npm run icons` after editing icons.json)', () => {
  const { ts, css } = buildIcons(loadInputs());
  assert.equal(readFileSync(OUTPUTS.ts, 'utf8'), ts, 'icons.generated.ts is stale: run npm run icons');
  assert.equal(readFileSync(OUTPUTS.css, 'utf8'), css, 'icons.generated.css is stale: run npm run icons');
});
